language: python
python:
    - "3.4"

before_install:
    - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.zip
    - unzip dynamodb_local_latest.zip
    - java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar &

install: "pip install -r requirements.txt"
script: "py.test tests/ --cov schema --cov-report term-missing"
after_success:
    - coveralls
